version: '2'

volumes:
  config:
  ssh_keypair:
  collections:

services:
  radicale:
    build: .
    image: fphammerle/radicale
    volumes:
    - config:/etc/radicale:ro
    - ssh_keypair:/var/lib/radicale/.ssh:rw
    - collections:/var/lib/radicale/collections:rw
    ports: ['0.0.0.0:5232:5232']
    restart: unless-stopped

# https://docs.docker.com/compose/compose-file/compose-file-v2/
